"""Add is_read to messages

Revision ID: 6605f7095eae
Revises: 
Create Date: 2026-04-16 02:52:16.168929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6605f7095eae'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_ai_alerts_acted_by_admin_id'), 'ai_alerts', ['acted_by_admin_id'], unique=False)
    op.create_index(op.f('ix_ai_alerts_airport_iata'), 'ai_alerts', ['airport_iata'], unique=False)
    op.create_index(op.f('ix_ai_alerts_decision'), 'ai_alerts', ['decision'], unique=False)
    op.create_index(op.f('ix_ai_alerts_flight_number'), 'ai_alerts', ['flight_number'], unique=False)
    op.alter_column('airlines', 'iata_code',
               existing_type=sa.CHAR(length=2),
               type_=sa.String(length=2),
               existing_nullable=False)
    op.alter_column('airports', 'iata_code',
               existing_type=sa.CHAR(length=3),
               type_=sa.String(length=3),
               existing_nullable=False)
    op.create_index(op.f('ix_flight_features_is_delayed'), 'flight_features', ['is_delayed'], unique=False)
    op.drop_constraint('flight_features_flight_id_fkey', 'flight_features', type_='foreignkey')
    op.create_foreign_key(None, 'flight_features', 'flights', ['flight_id'], ['id'])
    op.drop_index('idx_flights_dep', table_name='flights')
    op.drop_index('idx_flights_number', table_name='flights')
    op.drop_index('idx_flights_status', table_name='flights')
    op.drop_index('uq_flight_number_date', table_name='flights', postgresql_where='((flight_date IS NOT NULL) AND (flight_number IS NOT NULL))')
    op.create_index(op.f('ix_flights_dep_iata'), 'flights', ['dep_iata'], unique=False)
    op.create_index(op.f('ix_flights_flight_date'), 'flights', ['flight_date'], unique=False)
    op.create_index(op.f('ix_flights_flight_number'), 'flights', ['flight_number'], unique=False)
    op.create_index(op.f('ix_flights_scheduled_departure'), 'flights', ['scheduled_departure'], unique=False)
    op.create_index(op.f('ix_flights_status'), 'flights', ['status'], unique=False)
    op.alter_column('in_app_notifications', 'context',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index('ix_in_app_notif_read', table_name='in_app_notifications')
    op.drop_index('ix_in_app_notif_recipient', table_name='in_app_notifications')
    op.create_index(op.f('ix_in_app_notifications_is_read'), 'in_app_notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_in_app_notifications_kind'), 'in_app_notifications', ['kind'], unique=False)
    op.create_index(op.f('ix_in_app_notifications_recipient_user_id'), 'in_app_notifications', ['recipient_user_id'], unique=False)
    op.drop_index('idx_reply_message', table_name='message_replies')
    op.create_index(op.f('ix_message_replies_message_id'), 'message_replies', ['message_id'], unique=False)
    op.add_column('messages', sa.Column('is_read', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.drop_constraint('password_reset_tokens_token_key', 'password_reset_tokens', type_='unique')
    op.create_index(op.f('ix_password_reset_tokens_admin_id'), 'password_reset_tokens', ['admin_id'], unique=False)
    op.create_index(op.f('ix_password_reset_tokens_token'), 'password_reset_tokens', ['token'], unique=True)
    op.alter_column('predictions', 'shap_explanation',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index('idx_pred_flt', table_name='predictions')
    op.create_index(op.f('ix_predictions_flight_id'), 'predictions', ['flight_id'], unique=False)
    op.create_index(op.f('ix_predictions_flight_number'), 'predictions', ['flight_number'], unique=False)
    op.drop_constraint('predictions_flight_id_fkey', 'predictions', type_='foreignkey')
    op.create_foreign_key(None, 'predictions', 'flights', ['flight_id'], ['id'])
    op.drop_index('idx_users_role', table_name='users')
    op.drop_index('ix_users_employee_id_unique', table_name='users', postgresql_where="((employee_id IS NOT NULL) AND (TRIM(BOTH FROM employee_id) <> ''::text))")
    op.create_index(op.f('ix_users_employee_id'), 'users', ['employee_id'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.drop_index('uq_weather_airport_time', table_name='weather_conditions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_weather_airport_time', 'weather_conditions', ['airport_id', 'recorded_at'], unique=True)
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_employee_id'), table_name='users')
    op.create_index('ix_users_employee_id_unique', 'users', ['employee_id'], unique=True, postgresql_where="((employee_id IS NOT NULL) AND (TRIM(BOTH FROM employee_id) <> ''::text))")
    op.create_index('idx_users_role', 'users', ['role'], unique=False)
    op.drop_constraint(None, 'predictions', type_='foreignkey')
    op.create_foreign_key('predictions_flight_id_fkey', 'predictions', 'flights', ['flight_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_predictions_flight_number'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_flight_id'), table_name='predictions')
    op.create_index('idx_pred_flt', 'predictions', ['flight_id'], unique=False)
    op.alter_column('predictions', 'shap_explanation',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('ix_password_reset_tokens_token'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_admin_id'), table_name='password_reset_tokens')
    op.create_unique_constraint('password_reset_tokens_token_key', 'password_reset_tokens', ['token'])
    op.drop_column('messages', 'is_read')
    op.drop_index(op.f('ix_message_replies_message_id'), table_name='message_replies')
    op.create_index('idx_reply_message', 'message_replies', ['message_id'], unique=False)
    op.drop_index(op.f('ix_in_app_notifications_recipient_user_id'), table_name='in_app_notifications')
    op.drop_index(op.f('ix_in_app_notifications_kind'), table_name='in_app_notifications')
    op.drop_index(op.f('ix_in_app_notifications_is_read'), table_name='in_app_notifications')
    op.create_index('ix_in_app_notif_recipient', 'in_app_notifications', ['recipient_user_id'], unique=False)
    op.create_index('ix_in_app_notif_read', 'in_app_notifications', ['is_read'], unique=False)
    op.alter_column('in_app_notifications', 'context',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('ix_flights_status'), table_name='flights')
    op.drop_index(op.f('ix_flights_scheduled_departure'), table_name='flights')
    op.drop_index(op.f('ix_flights_flight_number'), table_name='flights')
    op.drop_index(op.f('ix_flights_flight_date'), table_name='flights')
    op.drop_index(op.f('ix_flights_dep_iata'), table_name='flights')
    op.create_index('uq_flight_number_date', 'flights', ['flight_number', 'flight_date'], unique=True, postgresql_where='((flight_date IS NOT NULL) AND (flight_number IS NOT NULL))')
    op.create_index('idx_flights_status', 'flights', ['status'], unique=False)
    op.create_index('idx_flights_number', 'flights', ['flight_number'], unique=False)
    op.create_index('idx_flights_dep', 'flights', ['scheduled_departure'], unique=False)
    op.drop_constraint(None, 'flight_features', type_='foreignkey')
    op.create_foreign_key('flight_features_flight_id_fkey', 'flight_features', 'flights', ['flight_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_flight_features_is_delayed'), table_name='flight_features')
    op.alter_column('airports', 'iata_code',
               existing_type=sa.String(length=3),
               type_=sa.CHAR(length=3),
               existing_nullable=False)
    op.alter_column('airlines', 'iata_code',
               existing_type=sa.String(length=2),
               type_=sa.CHAR(length=2),
               existing_nullable=False)
    op.drop_index(op.f('ix_ai_alerts_flight_number'), table_name='ai_alerts')
    op.drop_index(op.f('ix_ai_alerts_decision'), table_name='ai_alerts')
    op.drop_index(op.f('ix_ai_alerts_airport_iata'), table_name='ai_alerts')
    op.drop_index(op.f('ix_ai_alerts_acted_by_admin_id'), table_name='ai_alerts')
    # ### end Alembic commands ###
